version: '3.9'

services:
  redis:
    image: redis:7
    container_name: oee-redis
    ports:
      - "6379:6379"

  postgres:
    image: postgres:16
    container_name: oee-postgres
    environment:
      POSTGRES_DB: oee
      POSTGRES_USER: oee
      POSTGRES_PASSWORD: oee
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
